/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JournalsRouteImport } from './routes/journals'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JournalsJournalIdRouteImport } from './routes/journals_.$journalId'

const JournalsRoute = JournalsRouteImport.update({
  id: '/journals',
  path: '/journals',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalsJournalIdRoute = JournalsJournalIdRouteImport.update({
  id: '/journals_/$journalId',
  path: '/journals/$journalId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/journals': typeof JournalsRoute
  '/journals/$journalId': typeof JournalsJournalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/journals': typeof JournalsRoute
  '/journals/$journalId': typeof JournalsJournalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/journals': typeof JournalsRoute
  '/journals_/$journalId': typeof JournalsJournalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/journals' | '/journals/$journalId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/journals' | '/journals/$journalId'
  id: '__root__' | '/' | '/about' | '/journals' | '/journals_/$journalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  JournalsRoute: typeof JournalsRoute
  JournalsJournalIdRoute: typeof JournalsJournalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/journals': {
      id: '/journals'
      path: '/journals'
      fullPath: '/journals'
      preLoaderRoute: typeof JournalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journals_/$journalId': {
      id: '/journals_/$journalId'
      path: '/journals/$journalId'
      fullPath: '/journals/$journalId'
      preLoaderRoute: typeof JournalsJournalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  JournalsRoute: JournalsRoute,
  JournalsJournalIdRoute: JournalsJournalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
